language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
# latest node
before_install:
  - nvm install 7.4.0
# install dependencies
install:
  - npm install
  - npm run-script compile
  - cd py
  - pip install -e .
  - cd ..
# run tests
script:
  - if [[ $TRAVIS_PYTHON_VERSION = '3.6' ]]; then SCRIPT="coverage"; else SCRIPT="test"; fi
  - npm run-script $SCRIPT
  - cd py
  - python setup.py test
  - cd ..
# no emails
notifications:
  email: false
# run with containers
sudo: false
